image: node:latest

stages:
  - build
  - deploy

before_script:
  - npm install 

# Job One For making build
build:
  stage: build
  script:
    - export NODE_OPTIONS=--openssl-legacy-provider
    - npm run build -- --prod
  artifacts:
    paths:
      - ./dist/music/
  only: ['master']

# Job Two for deploy build to S3
deploy:
  image: python:latest
  stage: deploy
  before_script:
    - pip install awscli
  dependencies:
    - build
  script:
    - ls
    - aws s3 cp ./dist/music s3://musicweb/ --recursive
    - aws s3 sync ./dist/music s3://musicweb/ --delete
  only: ['master']