image: node:latest

stages:
  - build
  - deploy

before_script:
  - npm install 

# Job One For making build
build:
  stage: build
  script:
    - npm run build --prod
  only: ['master']

# Job Two for deploy build to S3
deploy:
  image: python:latest
  stage: deploy
  before_script:
    - pip install awscli
  script:
    - aws s3 sync ./dist s3://BUCKET_NAME/
  only: ['master']

# variables:
#   DOCKER_HOST : tcp://docker:2375/
#   DOCKER_DRIVER : overlay2
#   DOCKER_TLS_CERTDIR : "" # explain => https://about.gitlab.com/releases/2019/07/31/docker-in-docker-with-docker-19-dot-03/ 


# stages :
#   - build_image

# build_image :
#   stage : build_image
#   image : docker:stable
#   services :
#     - name : docker:dind
#       alias : docker
#       startup_timeout : 60
#   script :
#     - docker login -u lyoudr -p Awdxa48624
#     - docker build -t music_web:prod .
#     - docker tag music_web:prod lyoudr/music_web
#     - docker push lyoudr/music_web
#     - docker rmi music_web:prod
#   only : 
#     - other
#   tags :
#     - ann

# run locally =>
# gitlab-runner exec docker --docker-privileged build_image